trailingComma: 'es5'
lineWidth: 110
singleQuote: true
useTabs: true
overrides:
  - files:
      - '*.yml'
      - '*.yaml'
      - '*.json'
    options:
      tabWidth: 2
      trailingComma: 'none'
  - files:
      - '*.js'
    options:
      tabWidth: 4
      semi: true
